# Site settings
email: 
baseurl: 
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Scrub Party
description: 
url: ""
twitter_username: 
default_img: 

# Profile settings
name: Muhammad Syahrul Nizam
profile_img: https://i.imgur.com/ei0qVj7.jpg
profile: 
social: 
  github: syahrul12345

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
